### PR TITLE
Reload Button issue

### PR DESCRIPTION
**Pull request by gobbledy-gook**
### Summary
Now whenever reload button is pressed it reloads the current tab and the extension page.

### Details and comments
```c++
location.reload()
```
Added in ```popup.js``` under the btn4 function.

Closes issue #31

### CODE REVIEW

**Comment by gobbledy-gook** [comment]
Wait.. before review.. doing some UI Changes to the Reload Button !

**Comment by AnsahMohammad** [comment]
Alright, just request a review whenever you're ready!

**Comment by gobbledy-gook** [comment]
yes ready !

**Comment by AnsahMohammad** [comment]
That's a great fix

**Review by AnsahMohammad — APPROVED** [review]

**Pull request merged**
